// <auto-generated />
using System;
using DAP.Infrastructure.DataAccess.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAP.Infrastructure.DataAccess.Persistence.Migrations
{
    [DbContext(typeof(DataAcquisitionPlatformDbContext))]
    [Migration("20260917031558_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DAP.Core.Domain.Entities.CollectionDataRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at");

                    b.Property<Guid>("CollectionPointId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_point_id");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("metric_name");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_collection_data_records_collected_at");

                    b.HasIndex("CollectionPointId")
                        .HasDatabaseName("ix_collection_data_records_collection_point_id");

                    b.HasIndex("CollectionPointId", "MetricName", "CollectedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_collection_data_records_point_metric_collected_at");

                    b.ToTable("collection_data_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_collection_data_records_metric_name_not_blank", "btrim(metric_name) <> ''");

                            t.HasCheckConstraint("ck_collection_data_records_unit_not_blank", "btrim(unit) <> ''");
                        });
                });

            modelBuilder.Entity("DAP.Core.Domain.Entities.CollectionPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("CommunicationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("communication_status");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endpoint");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("protocol");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_collection_points_code");

                    b.HasIndex("CommunicationStatus", "UpdatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_collection_points_status_updated_at");

                    b.HasIndex("Source", "UpdatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_collection_points_source_updated_at");

                    b.ToTable("collection_points", null, t =>
                        {
                            t.HasCheckConstraint("ck_collection_points_code_not_blank", "btrim(code) <> ''");

                            t.HasCheckConstraint("ck_collection_points_code_upper", "code = upper(code)");

                            t.HasCheckConstraint("ck_collection_points_communication_status", "communication_status IN ('在线', '离线', '停用', '未知')");

                            t.HasCheckConstraint("ck_collection_points_endpoint_not_blank", "btrim(endpoint) <> ''");

                            t.HasCheckConstraint("ck_collection_points_name_not_blank", "btrim(name) <> ''");

                            t.HasCheckConstraint("ck_collection_points_protocol_not_blank", "btrim(protocol) <> ''");

                            t.HasCheckConstraint("ck_collection_points_source", "source IN ('Server', 'Local')");
                        });
                });

            modelBuilder.Entity("DAP.Core.Domain.Entities.ManagedDataDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcquisitionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("acquisition_type");

                    b.Property<string>("BusinessTagsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("business_tags_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<int>("CollectionIntervalSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(300)
                        .HasColumnName("collection_interval_seconds");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("ConnectionAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("connection_address");

                    b.Property<string>("DataCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("data_category");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("identifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ProcessCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("process_code");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_managed_data_definitions_code");

                    b.HasIndex("Department", "ProcessCode")
                        .HasDatabaseName("ix_managed_data_definitions_department_process_code");

                    b.HasIndex("AcquisitionType", "IsEnabled", "UpdatedAt")
                        .HasDatabaseName("ix_managed_data_definitions_type_enabled_updated_at");

                    b.ToTable("managed_data_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_managed_data_definitions_acquisition_type_not_blank", "btrim(acquisition_type) <> ''");

                            t.HasCheckConstraint("ck_managed_data_definitions_code_not_blank", "btrim(code) <> ''");

                            t.HasCheckConstraint("ck_managed_data_definitions_code_upper", "code = upper(code)");

                            t.HasCheckConstraint("ck_managed_data_definitions_connection_address_not_blank", "btrim(connection_address) <> ''");

                            t.HasCheckConstraint("ck_managed_data_definitions_data_category_not_blank", "btrim(data_category) <> ''");

                            t.HasCheckConstraint("ck_managed_data_definitions_department_not_blank", "btrim(department) <> ''");

                            t.HasCheckConstraint("ck_managed_data_definitions_identifier_not_blank", "btrim(identifier) <> ''");

                            t.HasCheckConstraint("ck_managed_data_definitions_interval_seconds_positive", "collection_interval_seconds > 0");

                            t.HasCheckConstraint("ck_managed_data_definitions_name_not_blank", "btrim(name) <> ''");

                            t.HasCheckConstraint("ck_managed_data_definitions_process_code_not_blank", "btrim(process_code) <> ''");
                        });
                });

            modelBuilder.Entity("DAP.Core.Domain.Entities.CollectionDataRecord", b =>
                {
                    b.HasOne("DAP.Core.Domain.Entities.CollectionPoint", "CollectionPoint")
                        .WithMany("Records")
                        .HasForeignKey("CollectionPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("collection_data_records_collection_point_id_fkey");

                    b.Navigation("CollectionPoint");
                });

            modelBuilder.Entity("DAP.Core.Domain.Entities.CollectionPoint", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
